### ISSUE TITLE
Consider holding sample data in commons.math classes

### ISSUE THREAD

**Issue by dmcg** [dmcg/kostings#8]
If we read the data directly into DescriptiveStatistics then could avoid recalculating them every matcher invocation? probablyLessThan and probablyMoreThan would have to not scale all samples to make this worthwhile

**Comment by stigmergist** [comment]
Sorted. Moved to use StatisticalSummary (interface) for PerformanceData. Allows us to use SummaryStatistics, too, which doesn't hold the data but just the calculated stats
